//
// Created by AILEE on 2023/3/9.
//

#ifndef SKY_SEGMENTATION_SERVER_APP_UTILS_HPP
#define SKY_SEGMENTATION_SERVER_APP_UTILS_HPP

#include "Utils.h"

#endif //SKY_SEGMENTATION_SERVER_APP_UTILS_HPP
